"use client"

import { useEffect } from "react"
import { X } from "lucide-react"
import { candidates } from "@/lib/data"

export function ExportModal({
  candidateId,
  blindMode,
  onClose,
}: {
  candidateId: string | null
  blindMode: boolean
  onClose: () => void
}) {
  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") onClose()
    }
    if (candidateId) window.addEventListener("keydown", onKey)
    return () => window.removeEventListener("keydown", onKey)
  }, [candidateId, onClose])

  if (!candidateId) return null
  const c = candidates.find((x) => x.id === candidateId)
  if (!c) return null

  const report = `CANDIDATE EVALUATION REPORT
============================
Candidate ID: ${c.id}   (Blind mode: ${blindMode ? "ON — name withheld" : "OFF"})
Name: ${blindMode ? "[redacted for blind review]" : c.name}
Role: ${c.role}          Stage: ${c.stage}

AI HIRING SCORE: ${c.aiScore ?? "—"} / 100        Recommendation: ${c.recommendation}
Bias Indicator: ${c.bias === "review" ? "REVIEW FLAG — manual adjudication required" : "Clear"}

MATCH BREAKDOWN
  Skill Match          ${c.skillMatch ?? "—"}%
  Experience Match     ${c.expMatch ?? "—"}%
  Education Match      ${c.eduMatch ?? "—"}%
  Certification Match  ${c.certMatch ?? "—"}%

SKILLS MATCHED
  ${c.skills.have.join(", ") || "—"}

MISSING SKILLS
  ${c.skills.missing.join(", ") || "None"}

AI RESUME SUMMARY
  ${c.summary}

RECRUITER NOTES
  ${c.notes || "(none entered)"}

Grounding: score generated from resume evidence + REQ job description + hiring
policy v3, retrieved via RAG. Report generated by Talent Lens AI Recruitment
Dashboard — for internal hiring-panel use only.`

  return (
    <div
      className="fixed inset-0 z-[100] flex items-center justify-center bg-ink/50 p-6"
      role="dialog"
      aria-modal="true"
      aria-label="Candidate evaluation report"
      onClick={onClose}
    >
      <div
        className="scroll-thin max-h-[82vh] w-full max-w-[560px] overflow-y-auto rounded-2xl bg-surface shadow-[0_8px_24px_rgba(18,22,28,0.10)]"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between border-b border-line px-6 py-4">
          <h4 className="font-display text-sm font-semibold">Candidate Evaluation Report</h4>
          <button
            type="button"
            onClick={onClose}
            className="rounded-md p-1 text-muted hover:bg-line-2"
            aria-label="Close"
          >
            <X className="h-4 w-4" aria-hidden />
          </button>
        </div>
        <div className="p-6">
          <pre className="whitespace-pre-wrap rounded-[10px] border border-line bg-[#fafaf9] p-3.5 font-mono text-[11.5px] leading-relaxed text-[#333]">
            {report}
          </pre>
          <button
            type="button"
            onClick={onClose}
            className="mt-3 w-full rounded-lg border border-ink bg-ink py-2.5 text-[12.8px] font-semibold text-white transition hover:brightness-110"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  )
}
